version: '2'
services:
    accouchementv3-app:
        image: accouchementv3
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://accouchementv3-postgresql:5432/accouchementV3
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    accouchementv3-postgresql:
        extends:
            file: postgresql.yml
            service: accouchementv3-postgresql
