version: '2'
services:
    accouchementv3-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/accouchementV3/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=accouchementV3
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
